name: markdown_example
description: An example app demonstrating the markdown package performance improvements.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  markdown:
    path: ../
  url_launcher: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true